version: "3"

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: golek_api_gateway
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./nginx/golek.gateway.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/errors.conf:/etc/nginx/conf.d/errors.conf

networks:
  default:
    name: golek_network_br
    external: true
